### ISSUE TITLE
Websocket URL for logs current is localhost:2121

### ISSUE THREAD

**Issue by naicoi92** [kubewall/kubewall#10]
https://github.com/kubewall/kubewall/blob/2149d53cd00d10fcc8721452298747a4ef883ed1/client/src/components/app/MiscDetailsContainer/Logs/SocketLogs/index.tsx#L49C5-L49C17

Please check this file. And fix cho new build.

**Comment by kshitijmehta** [comment]
@naicoi92 : Noted. We are looking at this.
Thanks for pointing it out.

**Comment by abhimanyu003** [comment]
We have released new version that resoles this issue:
You can download latest version from here https://github.com/kubewall/kubewall/releases/tag/v0.0.3

once again thanks so much for letting us know about this.
