### ISSUE TITLE
Contexts are not URL encoded

### ISSUE THREAD

**Issue by thomas-desforges** [kubewall/kubewall#24]
Hi,

I was just testing the project, well done! It looks promising.

I have a lot of context names using special characters (in my case `/`, ex: `region/env`).
In the app, the context names are used in the URL to navigate between clusters.
But since they are not url encoded, it fails and produce urls like `/config/region/env/list?resourcekind=pods` => 404 not found
If I encode the character manually, it works as expected.

**Comment by abhimanyu003** [comment]
Hello @thomas-desforges thanks for checking this out and letting us know. We are going to have a look and update this.
