### ISSUE TITLE
Hide kubectl.kubernetes.io/last-applied-configuration

### ISSUE THREAD

**Issue by Jonomir** [kubewall/kubewall#26]
Would be nice to be able to hide the `kubectl.kubernetes.io/last-applied-configuration` annotation in the overview (and maybe the YAML view as well)

Its a bit distracting when the first thing you see when clicking on an object, is a gigantic annotation.

**Comment by kshitijmehta** [comment]
@Jonomir we'll make some changes to the overview part in the next release. 
Thanks for the feedback!

**Comment by kshitijmehta** [comment]
@Jonomir  We have made changes as per you request. You can use the latest release `0.0.7`.

**Comment by Jonomir** [comment]
Awesome, you found the perfect middle ground of showing that its there, but not making it take the whole screen!
