### ISSUE TITLE
Sort pods by age

### ISSUE THREAD

**Issue by Jonomir** [kubewall/kubewall#27]
I like to see newest objects first.

Currently its not possible to sort pods by age

<img width="721" alt="image" src="https://github.com/user-attachments/assets/c8b73548-a552-4ba2-b6ee-5069f9859ffb">

For Deployments it works like a charm
<img width="812" alt="image" src="https://github.com/user-attachments/assets/b7124679-717f-4032-9415-3cdd117cc8f0">

**Comment by kshitijmehta** [comment]
@Jonomir we'll enable the sorting in the next release. 
Thanks for the feedback.

**Comment by kshitijmehta** [comment]
@Jonomir We have added the sorting feature. Please use the latest release. `0.0.7`.

**Comment by Jonomir** [comment]
Thanks a lot, works just as expected!
