### ISSUE TITLE
missing support for default EKS contexts

### ISSUE THREAD

**Issue by avielb-navina** [kubewall/kubewall#28]
hey! 
looks very cool! 
i was trying using it with EKS contexts (`arn:aws:eks:us-east-1:123123123123:cluster/my-cluster`) and it had issues.
after renaming the context to something like `my-cluster` it worked

**Comment by abhimanyu003** [comment]
Hello, @avielb-navina thanks so much for trying out and reporting the issue.
This is known as issue #24 and the fix will be available with the next release, till then please update the name and use it.
Let us know if you get anything.

**Comment by kshitijmehta** [comment]
@avielb-navina we had added the support of EKS naming. You can use the latest release `0.0.7`.
