### ISSUE TITLE
Not rendering SGR

### ISSUE THREAD

**Issue by javydekoning** [kubewall/kubewall#33]
Hi, great looking tool!

It doesn't current render "styled" log output (select graphic rendition).

![image](https://github.com/user-attachments/assets/9c54c213-31a4-4389-8a42-b885f740bc58)

Thanks!

**Comment by abhimanyu003** [comment]
This is updated and fixed in the latest release version v0.0.10 
Once again thanks for reporting the issue. 

Feel free to open a new issue if you are still facing the problem.
