### ISSUE TITLE
Ability to Sync Kubeconfig files from a config directory

### ISSUE THREAD

**Issue by adityati** [kubewall/kubewall#38]
Would be nice to have all the kubeconfig files snyced from a specific directory as this would avoid adding every cluster kubeconfig individually.

**Comment by abhimanyu003** [comment]
Hello @adityati 
Thanks so much for trying out and sharing your thoughts.

We are scanning all the kubeconfig in `~/.kube` folder.

What you can also do is copy all your kube-config files to `~/.kubewall/kubeconfigs` in that way you will also have a copy just for "kubewall"

**Comment by adityati** [comment]
I do have all my kubeconfig files under ~/.kube/configs/. It does not scan all the config files.

**Comment by abhimanyu003** [comment]
Looks like you have a sub-folder under `~/kube/config` we only scan files in the top lever-folder and not-subfolder of:

* `~/.kube`
* `~/.kubewall/kubeconfigs`

What you can also do is create a symlink.

```sh
ln -s ~/.kube/config/ ~/.kubewall/kubeconfigs 
```

**Comment by adityati** [comment]
yes, symlink is working. Thankyou

**Comment by OneCricketeer** [comment]
Should it not also respect `$KUBECONFIG` variable on startup?

**Comment by miran248** [comment]
> Should it not also respect `$KUBECONFIG` variable on startup?

It should!

I maintain separate `kube-config` files, one per cluster, each in its own folder, to ensure i can never deploy something on a wrong cluster.
`kubectl`, `k9s`, .. all support `KUBECONFIG` env var.
```shell
> KUBECONFIG=kube-config k9s
```
