### ISSUE TITLE
UI not working - CORS/bad hostname

### ISSUE THREAD

**Issue by geekprotem** [kubewall/kubewall#39]
Installed with brew, but the same thing happens while running docker locally on macOS.  Tested with Safari and Brave with the same effect on both.  Connecting to EKS clusters with modified config files to bypass known URL encoding issue.

The UI and API both run on different hostnames, so the browser will only load data when security settings are disabled so that 'localhost:7080' can issue API requests to, for example, '1727870757065.localhost:7080'.
No errors show up outside of the browser console.

Recommend removing that first hostname from the API requests, running API and UI on separate ports, or at least updating documentation noting that some security settings (CORS) may need to be disabled to allow things to work properly.

**Comment by abhimanyu003** [comment]
Hello @geekprotem,

It seems that Safari and Brave browsers aren't allowing wildcard subdomains for localhost. The random numbers in front of localhost, like 1727870757065, are used to bypass the default SSE limit of 6 connections.

**What you can do:**

* Use the IP address http://127.0.0.1:7080/
* **Use HTTPS (recommended),** this is best you will not any-issue at all after this. 

We will see what we can do more in up-coming release, we have a small doc on about how to generate self-signed cert using mkcert.
