### ISSUE TITLE
Container Restarts not showing in Pod view

### ISSUE THREAD

**Issue by kenlasko** [kubewall/kubewall#41]
Just want to start off by saying that I'm quite impressed with the quality of Kubewall so far. It may soon replace Headlamp as my go-to for web-based Kubernetes monitoring. 

I have found a minor issue where the values for `Restarts`, `Restart Reason` and `Last Restart` and maybe `Command`, are not populated. In its place, I only see a dash. I can see `Restarts` and `Last Restart` properly from the pod list view.

Running Kubernetes 1.31.1 on Talos 1.8.0

![image](https://github.com/user-attachments/assets/4ceebb8c-2144-4549-848c-4a5516c73e72)

**Comment by abhimanyu003** [comment]
@kenlasko This is fixed in the latest release `v0.0.8` and should work well along with the additional features let us know how it goes.

**Comment by abhimanyu003** [comment]
I'm closing this one, feel free to open new if you face any issue.
