### ISSUE TITLE
How to exec into the container or pod

### ISSUE THREAD

**Issue by snail2sky** [kubewall/kubewall#47]
Sometimes I need to log in to the container to debug my program, but it seems that it can't be done at the moment.

**Comment by snail2sky** [comment]
Similar to using kubectl exec pod -c CONTAINER -- sh

**Comment by aslafy-z** [comment]
This is a duplicate of #40

**Comment by abhimanyu003** [comment]
Thanks so much for trying and feature suggestion. 
Also, thanks @aslafy-z for noticing it's duplicate. 

Sure we are working on SSH / Web-shell feature and will release an update soon.

I'm closing this in favor of #40

**Comment by waldner** [comment]
Any news on this one?
