### ISSUE TITLE
Pod keeps restarting after few minutes when liveliness probes failed

### ISSUE THREAD

**Issue by vishal602** [kubewall/kubewall#51]
The pod is in the restart loop after few minutes due to failing in liveliness probe . 
![Kubewall](https://github.com/user-attachments/assets/27c85cd4-a3e8-4990-8dc6-e874db3c0bdf)

Liveness probe failed: Get "https://10.14.2.42:8443/healthz": unexpected EOF.

![Kubewall](https://github.com/user-attachments/assets/0ae01441-e1b9-448e-beed-e83259608f9f)

Picture attached for your reference. Kubewall is current installed in cluster using Helm without any customization of helm values

**Comment by abhimanyu003** [comment]
Hello @vishal602 
Thanks so much for trying and letting us know about the issue.
This is now resolved in v0.0.9, please update your heml chart, maybe uninstall it once and then update.

Let us know if you face any issue

Once again thanks so much.
