### ISSUE TITLE
Show Type and LoadBalancer IP for services

### ISSUE THREAD

**Issue by ams0** [kubewall/kubewall#54]
In the Network -> Services section, the type of service is not shown, and in case of LoadBalancer type, the only way to get it is to examine the YAML of the service.

**Comment by abhimanyu003** [comment]
Hello @ams0 we will add this in next release.

**Comment by abhimanyu003** [comment]
This is updated and fixed in the latest release version v0.0.10 
Once again thanks for reporting the issue. 

Feel free to open a new issue if you are still facing the problem.
