### ISSUE TITLE
Problem with infinity loading

### ISSUE THREAD

**Issue by nota-user** [kubewall/kubewall#55]
When I try to use yaml I get an infinity loading
![Eternal loading](https://github.com/user-attachments/assets/711b8304-678a-4d35-950d-6a810f8fe83a)
A similar problem occurs if I connect via fvdn, but in this case nothing is loaded at all
![with fqdn](https://github.com/user-attachments/assets/205bbc92-1749-4080-b891-fdd79104813b)
I use Rocky Linux 9 with binary kubewall
K8s version 1.28

**Comment by abhimanyu003** [comment]
Hello @nota-user 

Can you please try `127.0.0.1:7080` instead of `localhost:7080`.
Also if possible can you please try with `HTTPS` once.


Thanks

**Comment by nota-user** [comment]
Sorry. Error was in the browser, not in the program. Its not working, because im using it in offline
The browser is trying to download monaco-editor from the Internet.
![Снимок](https://github.com/user-attachments/assets/9423d350-8c84-4ca2-b93e-89afc947ab00)

**Comment by nota-user** [comment]
If I understand correctly, somewhere inм kubewall it there is a link for monaco-editor embedded and therefore it is not possible to use it in an offline environment. Access to DNS names is also impossible.

**Comment by kshitijmehta** [comment]
Yes, currently the monaco-editor uses cdn. 
We'll see to add the offline feature as well in upcoming releases.

**Comment by abhimanyu003** [comment]
This is updated and fixed in the latest release version v0.0.10 
Once again thanks for reporting the issue. 

Feel free to open a new issue if you are still facing the problem.
